//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.11.28 at 03:46:45 PM GMT 
//


package org.nees.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Acknowledgement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Acknowledgement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="projid" type="{}IDnumber"/>
 *         &lt;element name="expid" type="{}IDnumber"/>
 *         &lt;element name="trialid" type="{}IDnumber"/>
 *         &lt;element name="sponsor" type="{}String255"/>
 *         &lt;element name="howToCite" type="{}Text"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ackid" use="required" type="{}IDnumber" />
 *       &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Acknowledgement", propOrder = {
    "projid",
    "expid",
    "trialid",
    "sponsor",
    "howToCite"
})
public class Acknowledgement {

    @XmlElementRef(name = "projid", type = JAXBElement.class)
    protected JAXBElement<Integer> projid;
    @XmlElementRef(name = "expid", type = JAXBElement.class)
    protected JAXBElement<Integer> expid;
    @XmlElementRef(name = "trialid", type = JAXBElement.class)
    protected JAXBElement<Integer> trialid;
    @XmlElementRef(name = "sponsor", type = JAXBElement.class)
    protected JAXBElement<String> sponsor;
    @XmlElementRef(name = "howToCite", type = JAXBElement.class)
    protected JAXBElement<String> howToCite;
    @XmlAttribute(required = true)
    protected int ackid;
    @XmlAttribute
    protected String link;

    /**
     * Gets the value of the projid property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getProjid() {
        return projid;
    }

    /**
     * Sets the value of the projid property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setProjid(JAXBElement<Integer> value) {
        this.projid = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the expid property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getExpid() {
        return expid;
    }

    /**
     * Sets the value of the expid property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setExpid(JAXBElement<Integer> value) {
        this.expid = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the trialid property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getTrialid() {
        return trialid;
    }

    /**
     * Sets the value of the trialid property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setTrialid(JAXBElement<Integer> value) {
        this.trialid = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the sponsor property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSponsor() {
        return sponsor;
    }

    /**
     * Sets the value of the sponsor property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSponsor(JAXBElement<String> value) {
        this.sponsor = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the howToCite property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getHowToCite() {
        return howToCite;
    }

    /**
     * Sets the value of the howToCite property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setHowToCite(JAXBElement<String> value) {
        this.howToCite = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the ackid property.
     * 
     */
    public int getAckid() {
        return ackid;
    }

    /**
     * Sets the value of the ackid property.
     * 
     */
    public void setAckid(int value) {
        this.ackid = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLink(String value) {
        this.link = value;
    }

}
