//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.11.28 at 03:46:45 PM GMT 
//


package org.nees.data;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Representation of whole or part(s) of
 *       NEEScentral.
 * 
 * <p>Java class for central complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="central">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Project" type="{}Project" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Experiment" type="{}Experiment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Simulation" type="{}Simulation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CoordinateSpace" type="{}CoordinateSpace" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CoordinateSpaceDataFile" type="{}CoordinateSpaceDataFile" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Trial" type="{}Trial" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SimulationRun" type="{}SimulationRun" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DAQConfig" type="{}DAQConfig" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ControllerConfig" type="{}ControllerConfig" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DAQChannel" type="{}DAQChannel" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ControllerChannel" type="{}ControllerChannel" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Repetition" type="{}Repetition" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SensorLocationPlan" type="{}SensorLocationPlan" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SourceLocationPlan" type="{}SourceLocationPlan" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SensorLocation" type="{}SensorLocation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SourceLocation" type="{}SourceLocation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SensorPool" type="{}SensorPool" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Material" type="{}Material" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MaterialProperty" type="{}MaterialProperty" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MaterialFile" type="{}MaterialFile" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SimilitudeLawValue" type="{}SimilitudeLawValue" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MaterialType" type="{}MaterialType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MaterialTypeProperty" type="{}MaterialTypeProperty" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SensorManifest" type="{}SensorManifest" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SensorSensorManifest" type="{}SensorSensorManifest" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SensorType" type="{}SensorType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CoordinateSystem" type="{}CoordinateSystem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CoordinateDimension" type="{}CoordinateDimension" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MeasurementUnitConversion" type="{}MeasurementUnitConversion" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MeasurementUnitCategory" type="{}MeasurementUnitCategory" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MeasurementUnit" type="{}MeasurementUnit" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EquipmentClass" type="{}EquipmentClass" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Facility" type="{}Facility" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Organization" type="{}Organization" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TrainingAndCertification" type="{}TrainingAndCertification" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Equipment" type="{}Equipment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EquipmentDocumentation" type="{}EquipmentDocumentation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EquipmentAttribute" type="{}EquipmentAttribute" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ExperimentEquipment" type="{}ExperimentEquipment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Attribute" type="{}Attribute" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DataFile" type="{}DataFile" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DocumentFormat" type="{}DocumentFormat" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ExperimentDomain" type="{}ExperimentDomain" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SimilitudeLawGroup" type="{}SimilitudeLawGroup" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SimilitudeLaw" type="{}SimilitudeLaw" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SensorModel" type="{}SensorModel" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Sensor" type="{}Sensor" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Calibration" type="{}Calibration" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Acknowledgement" type="{}Acknowledgement" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "central", propOrder = {
    "project",
    "experiment",
    "simulation",
    "coordinateSpace",
    "coordinateSpaceDataFile",
    "trial",
    "simulationRun",
    "daqConfig",
    "controllerConfig",
    "daqChannel",
    "controllerChannel",
    "repetition",
    "sensorLocationPlan",
    "sourceLocationPlan",
    "sensorLocation",
    "sourceLocation",
    "sensorPool",
    "material",
    "materialProperty",
    "materialFile",
    "similitudeLawValue",
    "materialType",
    "materialTypeProperty",
    "sensorManifest",
    "sensorSensorManifest",
    "sensorType",
    "coordinateSystem",
    "coordinateDimension",
    "measurementUnitConversion",
    "measurementUnitCategory",
    "measurementUnit",
    "equipmentClass",
    "facility",
    "organization",
    "trainingAndCertification",
    "equipment",
    "equipmentDocumentation",
    "equipmentAttribute",
    "experimentEquipment",
    "attribute",
    "dataFile",
    "documentFormat",
    "experimentDomain",
    "similitudeLawGroup",
    "similitudeLaw",
    "sensorModel",
    "sensor",
    "calibration",
    "acknowledgement"
})
public class Central {

    @XmlElement(name = "Project")
    protected List<Project> project;
    @XmlElement(name = "Experiment")
    protected List<Experiment> experiment;
    @XmlElement(name = "Simulation")
    protected List<Simulation> simulation;
    @XmlElement(name = "CoordinateSpace")
    protected List<CoordinateSpace> coordinateSpace;
    @XmlElement(name = "CoordinateSpaceDataFile")
    protected List<CoordinateSpaceDataFile> coordinateSpaceDataFile;
    @XmlElement(name = "Trial")
    protected List<Trial> trial;
    @XmlElement(name = "SimulationRun")
    protected List<SimulationRun> simulationRun;
    @XmlElement(name = "DAQConfig")
    protected List<DAQConfig> daqConfig;
    @XmlElement(name = "ControllerConfig")
    protected List<ControllerConfig> controllerConfig;
    @XmlElement(name = "DAQChannel")
    protected List<DAQChannel> daqChannel;
    @XmlElement(name = "ControllerChannel")
    protected List<ControllerChannel> controllerChannel;
    @XmlElement(name = "Repetition")
    protected List<Repetition> repetition;
    @XmlElement(name = "SensorLocationPlan")
    protected List<SensorLocationPlan> sensorLocationPlan;
    @XmlElement(name = "SourceLocationPlan")
    protected List<SourceLocationPlan> sourceLocationPlan;
    @XmlElement(name = "SensorLocation")
    protected List<SensorLocation> sensorLocation;
    @XmlElement(name = "SourceLocation")
    protected List<SourceLocation> sourceLocation;
    @XmlElement(name = "SensorPool")
    protected List<SensorPool> sensorPool;
    @XmlElement(name = "Material")
    protected List<Material> material;
    @XmlElement(name = "MaterialProperty")
    protected List<MaterialProperty> materialProperty;
    @XmlElement(name = "MaterialFile")
    protected List<MaterialFile> materialFile;
    @XmlElement(name = "SimilitudeLawValue")
    protected List<SimilitudeLawValue> similitudeLawValue;
    @XmlElement(name = "MaterialType")
    protected List<MaterialType> materialType;
    @XmlElement(name = "MaterialTypeProperty")
    protected List<MaterialTypeProperty> materialTypeProperty;
    @XmlElement(name = "SensorManifest")
    protected List<SensorManifest> sensorManifest;
    @XmlElement(name = "SensorSensorManifest")
    protected List<SensorSensorManifest> sensorSensorManifest;
    @XmlElement(name = "SensorType")
    protected List<SensorType> sensorType;
    @XmlElement(name = "CoordinateSystem")
    protected List<CoordinateSystem> coordinateSystem;
    @XmlElement(name = "CoordinateDimension")
    protected List<CoordinateDimension> coordinateDimension;
    @XmlElement(name = "MeasurementUnitConversion")
    protected List<MeasurementUnitConversion> measurementUnitConversion;
    @XmlElement(name = "MeasurementUnitCategory")
    protected List<MeasurementUnitCategory> measurementUnitCategory;
    @XmlElement(name = "MeasurementUnit")
    protected List<MeasurementUnit> measurementUnit;
    @XmlElement(name = "EquipmentClass")
    protected List<EquipmentClass> equipmentClass;
    @XmlElement(name = "Facility")
    protected List<Facility> facility;
    @XmlElement(name = "Organization")
    protected List<Organization> organization;
    @XmlElement(name = "TrainingAndCertification")
    protected List<TrainingAndCertification> trainingAndCertification;
    @XmlElement(name = "Equipment")
    protected List<Equipment> equipment;
    @XmlElement(name = "EquipmentDocumentation")
    protected List<EquipmentDocumentation> equipmentDocumentation;
    @XmlElement(name = "EquipmentAttribute")
    protected List<EquipmentAttribute> equipmentAttribute;
    @XmlElement(name = "ExperimentEquipment")
    protected List<ExperimentEquipment> experimentEquipment;
    @XmlElement(name = "Attribute")
    protected List<Attribute> attribute;
    @XmlElement(name = "DataFile")
    protected List<DataFile> dataFile;
    @XmlElement(name = "DocumentFormat")
    protected List<DocumentFormat> documentFormat;
    @XmlElement(name = "ExperimentDomain")
    protected List<ExperimentDomain> experimentDomain;
    @XmlElement(name = "SimilitudeLawGroup")
    protected List<SimilitudeLawGroup> similitudeLawGroup;
    @XmlElement(name = "SimilitudeLaw")
    protected List<SimilitudeLaw> similitudeLaw;
    @XmlElement(name = "SensorModel")
    protected List<SensorModel> sensorModel;
    @XmlElement(name = "Sensor")
    protected List<Sensor> sensor;
    @XmlElement(name = "Calibration")
    protected List<Calibration> calibration;
    @XmlElement(name = "Acknowledgement")
    protected List<Acknowledgement> acknowledgement;

    /**
     * Gets the value of the project property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the project property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Project }
     * 
     * 
     */
    public List<Project> getProject() {
        if (project == null) {
            project = new ArrayList<Project>();
        }
        return this.project;
    }

    /**
     * Gets the value of the experiment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the experiment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExperiment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Experiment }
     * 
     * 
     */
    public List<Experiment> getExperiment() {
        if (experiment == null) {
            experiment = new ArrayList<Experiment>();
        }
        return this.experiment;
    }

    /**
     * Gets the value of the simulation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the simulation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimulation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Simulation }
     * 
     * 
     */
    public List<Simulation> getSimulation() {
        if (simulation == null) {
            simulation = new ArrayList<Simulation>();
        }
        return this.simulation;
    }

    /**
     * Gets the value of the coordinateSpace property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coordinateSpace property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoordinateSpace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoordinateSpace }
     * 
     * 
     */
    public List<CoordinateSpace> getCoordinateSpace() {
        if (coordinateSpace == null) {
            coordinateSpace = new ArrayList<CoordinateSpace>();
        }
        return this.coordinateSpace;
    }

    /**
     * Gets the value of the coordinateSpaceDataFile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coordinateSpaceDataFile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoordinateSpaceDataFile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoordinateSpaceDataFile }
     * 
     * 
     */
    public List<CoordinateSpaceDataFile> getCoordinateSpaceDataFile() {
        if (coordinateSpaceDataFile == null) {
            coordinateSpaceDataFile = new ArrayList<CoordinateSpaceDataFile>();
        }
        return this.coordinateSpaceDataFile;
    }

    /**
     * Gets the value of the trial property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trial property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrial().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Trial }
     * 
     * 
     */
    public List<Trial> getTrial() {
        if (trial == null) {
            trial = new ArrayList<Trial>();
        }
        return this.trial;
    }

    /**
     * Gets the value of the simulationRun property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the simulationRun property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimulationRun().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimulationRun }
     * 
     * 
     */
    public List<SimulationRun> getSimulationRun() {
        if (simulationRun == null) {
            simulationRun = new ArrayList<SimulationRun>();
        }
        return this.simulationRun;
    }

    /**
     * Gets the value of the daqConfig property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the daqConfig property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDAQConfig().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DAQConfig }
     * 
     * 
     */
    public List<DAQConfig> getDAQConfig() {
        if (daqConfig == null) {
            daqConfig = new ArrayList<DAQConfig>();
        }
        return this.daqConfig;
    }

    /**
     * Gets the value of the controllerConfig property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the controllerConfig property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getControllerConfig().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ControllerConfig }
     * 
     * 
     */
    public List<ControllerConfig> getControllerConfig() {
        if (controllerConfig == null) {
            controllerConfig = new ArrayList<ControllerConfig>();
        }
        return this.controllerConfig;
    }

    /**
     * Gets the value of the daqChannel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the daqChannel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDAQChannel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DAQChannel }
     * 
     * 
     */
    public List<DAQChannel> getDAQChannel() {
        if (daqChannel == null) {
            daqChannel = new ArrayList<DAQChannel>();
        }
        return this.daqChannel;
    }

    /**
     * Gets the value of the controllerChannel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the controllerChannel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getControllerChannel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ControllerChannel }
     * 
     * 
     */
    public List<ControllerChannel> getControllerChannel() {
        if (controllerChannel == null) {
            controllerChannel = new ArrayList<ControllerChannel>();
        }
        return this.controllerChannel;
    }

    /**
     * Gets the value of the repetition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the repetition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRepetition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Repetition }
     * 
     * 
     */
    public List<Repetition> getRepetition() {
        if (repetition == null) {
            repetition = new ArrayList<Repetition>();
        }
        return this.repetition;
    }

    /**
     * Gets the value of the sensorLocationPlan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sensorLocationPlan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSensorLocationPlan().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SensorLocationPlan }
     * 
     * 
     */
    public List<SensorLocationPlan> getSensorLocationPlan() {
        if (sensorLocationPlan == null) {
            sensorLocationPlan = new ArrayList<SensorLocationPlan>();
        }
        return this.sensorLocationPlan;
    }

    /**
     * Gets the value of the sourceLocationPlan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceLocationPlan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceLocationPlan().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SourceLocationPlan }
     * 
     * 
     */
    public List<SourceLocationPlan> getSourceLocationPlan() {
        if (sourceLocationPlan == null) {
            sourceLocationPlan = new ArrayList<SourceLocationPlan>();
        }
        return this.sourceLocationPlan;
    }

    /**
     * Gets the value of the sensorLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sensorLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSensorLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SensorLocation }
     * 
     * 
     */
    public List<SensorLocation> getSensorLocation() {
        if (sensorLocation == null) {
            sensorLocation = new ArrayList<SensorLocation>();
        }
        return this.sensorLocation;
    }

    /**
     * Gets the value of the sourceLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SourceLocation }
     * 
     * 
     */
    public List<SourceLocation> getSourceLocation() {
        if (sourceLocation == null) {
            sourceLocation = new ArrayList<SourceLocation>();
        }
        return this.sourceLocation;
    }

    /**
     * Gets the value of the sensorPool property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sensorPool property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSensorPool().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SensorPool }
     * 
     * 
     */
    public List<SensorPool> getSensorPool() {
        if (sensorPool == null) {
            sensorPool = new ArrayList<SensorPool>();
        }
        return this.sensorPool;
    }

    /**
     * Gets the value of the material property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the material property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMaterial().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Material }
     * 
     * 
     */
    public List<Material> getMaterial() {
        if (material == null) {
            material = new ArrayList<Material>();
        }
        return this.material;
    }

    /**
     * Gets the value of the materialProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the materialProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMaterialProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MaterialProperty }
     * 
     * 
     */
    public List<MaterialProperty> getMaterialProperty() {
        if (materialProperty == null) {
            materialProperty = new ArrayList<MaterialProperty>();
        }
        return this.materialProperty;
    }

    /**
     * Gets the value of the materialFile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the materialFile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMaterialFile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MaterialFile }
     * 
     * 
     */
    public List<MaterialFile> getMaterialFile() {
        if (materialFile == null) {
            materialFile = new ArrayList<MaterialFile>();
        }
        return this.materialFile;
    }

    /**
     * Gets the value of the similitudeLawValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the similitudeLawValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimilitudeLawValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimilitudeLawValue }
     * 
     * 
     */
    public List<SimilitudeLawValue> getSimilitudeLawValue() {
        if (similitudeLawValue == null) {
            similitudeLawValue = new ArrayList<SimilitudeLawValue>();
        }
        return this.similitudeLawValue;
    }

    /**
     * Gets the value of the materialType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the materialType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMaterialType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MaterialType }
     * 
     * 
     */
    public List<MaterialType> getMaterialType() {
        if (materialType == null) {
            materialType = new ArrayList<MaterialType>();
        }
        return this.materialType;
    }

    /**
     * Gets the value of the materialTypeProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the materialTypeProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMaterialTypeProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MaterialTypeProperty }
     * 
     * 
     */
    public List<MaterialTypeProperty> getMaterialTypeProperty() {
        if (materialTypeProperty == null) {
            materialTypeProperty = new ArrayList<MaterialTypeProperty>();
        }
        return this.materialTypeProperty;
    }

    /**
     * Gets the value of the sensorManifest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sensorManifest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSensorManifest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SensorManifest }
     * 
     * 
     */
    public List<SensorManifest> getSensorManifest() {
        if (sensorManifest == null) {
            sensorManifest = new ArrayList<SensorManifest>();
        }
        return this.sensorManifest;
    }

    /**
     * Gets the value of the sensorSensorManifest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sensorSensorManifest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSensorSensorManifest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SensorSensorManifest }
     * 
     * 
     */
    public List<SensorSensorManifest> getSensorSensorManifest() {
        if (sensorSensorManifest == null) {
            sensorSensorManifest = new ArrayList<SensorSensorManifest>();
        }
        return this.sensorSensorManifest;
    }

    /**
     * Gets the value of the sensorType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sensorType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSensorType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SensorType }
     * 
     * 
     */
    public List<SensorType> getSensorType() {
        if (sensorType == null) {
            sensorType = new ArrayList<SensorType>();
        }
        return this.sensorType;
    }

    /**
     * Gets the value of the coordinateSystem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coordinateSystem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoordinateSystem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoordinateSystem }
     * 
     * 
     */
    public List<CoordinateSystem> getCoordinateSystem() {
        if (coordinateSystem == null) {
            coordinateSystem = new ArrayList<CoordinateSystem>();
        }
        return this.coordinateSystem;
    }

    /**
     * Gets the value of the coordinateDimension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coordinateDimension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoordinateDimension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoordinateDimension }
     * 
     * 
     */
    public List<CoordinateDimension> getCoordinateDimension() {
        if (coordinateDimension == null) {
            coordinateDimension = new ArrayList<CoordinateDimension>();
        }
        return this.coordinateDimension;
    }

    /**
     * Gets the value of the measurementUnitConversion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measurementUnitConversion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeasurementUnitConversion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeasurementUnitConversion }
     * 
     * 
     */
    public List<MeasurementUnitConversion> getMeasurementUnitConversion() {
        if (measurementUnitConversion == null) {
            measurementUnitConversion = new ArrayList<MeasurementUnitConversion>();
        }
        return this.measurementUnitConversion;
    }

    /**
     * Gets the value of the measurementUnitCategory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measurementUnitCategory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeasurementUnitCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeasurementUnitCategory }
     * 
     * 
     */
    public List<MeasurementUnitCategory> getMeasurementUnitCategory() {
        if (measurementUnitCategory == null) {
            measurementUnitCategory = new ArrayList<MeasurementUnitCategory>();
        }
        return this.measurementUnitCategory;
    }

    /**
     * Gets the value of the measurementUnit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measurementUnit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeasurementUnit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeasurementUnit }
     * 
     * 
     */
    public List<MeasurementUnit> getMeasurementUnit() {
        if (measurementUnit == null) {
            measurementUnit = new ArrayList<MeasurementUnit>();
        }
        return this.measurementUnit;
    }

    /**
     * Gets the value of the equipmentClass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipmentClass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipmentClass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EquipmentClass }
     * 
     * 
     */
    public List<EquipmentClass> getEquipmentClass() {
        if (equipmentClass == null) {
            equipmentClass = new ArrayList<EquipmentClass>();
        }
        return this.equipmentClass;
    }

    /**
     * Gets the value of the facility property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the facility property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFacility().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Facility }
     * 
     * 
     */
    public List<Facility> getFacility() {
        if (facility == null) {
            facility = new ArrayList<Facility>();
        }
        return this.facility;
    }

    /**
     * Gets the value of the organization property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organization property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganization().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Organization }
     * 
     * 
     */
    public List<Organization> getOrganization() {
        if (organization == null) {
            organization = new ArrayList<Organization>();
        }
        return this.organization;
    }

    /**
     * Gets the value of the trainingAndCertification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trainingAndCertification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrainingAndCertification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrainingAndCertification }
     * 
     * 
     */
    public List<TrainingAndCertification> getTrainingAndCertification() {
        if (trainingAndCertification == null) {
            trainingAndCertification = new ArrayList<TrainingAndCertification>();
        }
        return this.trainingAndCertification;
    }

    /**
     * Gets the value of the equipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Equipment }
     * 
     * 
     */
    public List<Equipment> getEquipment() {
        if (equipment == null) {
            equipment = new ArrayList<Equipment>();
        }
        return this.equipment;
    }

    /**
     * Gets the value of the equipmentDocumentation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipmentDocumentation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipmentDocumentation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EquipmentDocumentation }
     * 
     * 
     */
    public List<EquipmentDocumentation> getEquipmentDocumentation() {
        if (equipmentDocumentation == null) {
            equipmentDocumentation = new ArrayList<EquipmentDocumentation>();
        }
        return this.equipmentDocumentation;
    }

    /**
     * Gets the value of the equipmentAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipmentAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipmentAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EquipmentAttribute }
     * 
     * 
     */
    public List<EquipmentAttribute> getEquipmentAttribute() {
        if (equipmentAttribute == null) {
            equipmentAttribute = new ArrayList<EquipmentAttribute>();
        }
        return this.equipmentAttribute;
    }

    /**
     * Gets the value of the experimentEquipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the experimentEquipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExperimentEquipment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExperimentEquipment }
     * 
     * 
     */
    public List<ExperimentEquipment> getExperimentEquipment() {
        if (experimentEquipment == null) {
            experimentEquipment = new ArrayList<ExperimentEquipment>();
        }
        return this.experimentEquipment;
    }

    /**
     * Gets the value of the attribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Attribute }
     * 
     * 
     */
    public List<Attribute> getAttribute() {
        if (attribute == null) {
            attribute = new ArrayList<Attribute>();
        }
        return this.attribute;
    }

    /**
     * Gets the value of the dataFile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataFile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataFile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataFile }
     * 
     * 
     */
    public List<DataFile> getDataFile() {
        if (dataFile == null) {
            dataFile = new ArrayList<DataFile>();
        }
        return this.dataFile;
    }

    /**
     * Gets the value of the documentFormat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentFormat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentFormat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentFormat }
     * 
     * 
     */
    public List<DocumentFormat> getDocumentFormat() {
        if (documentFormat == null) {
            documentFormat = new ArrayList<DocumentFormat>();
        }
        return this.documentFormat;
    }

    /**
     * Gets the value of the experimentDomain property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the experimentDomain property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExperimentDomain().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExperimentDomain }
     * 
     * 
     */
    public List<ExperimentDomain> getExperimentDomain() {
        if (experimentDomain == null) {
            experimentDomain = new ArrayList<ExperimentDomain>();
        }
        return this.experimentDomain;
    }

    /**
     * Gets the value of the similitudeLawGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the similitudeLawGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimilitudeLawGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimilitudeLawGroup }
     * 
     * 
     */
    public List<SimilitudeLawGroup> getSimilitudeLawGroup() {
        if (similitudeLawGroup == null) {
            similitudeLawGroup = new ArrayList<SimilitudeLawGroup>();
        }
        return this.similitudeLawGroup;
    }

    /**
     * Gets the value of the similitudeLaw property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the similitudeLaw property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimilitudeLaw().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimilitudeLaw }
     * 
     * 
     */
    public List<SimilitudeLaw> getSimilitudeLaw() {
        if (similitudeLaw == null) {
            similitudeLaw = new ArrayList<SimilitudeLaw>();
        }
        return this.similitudeLaw;
    }

    /**
     * Gets the value of the sensorModel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sensorModel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSensorModel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SensorModel }
     * 
     * 
     */
    public List<SensorModel> getSensorModel() {
        if (sensorModel == null) {
            sensorModel = new ArrayList<SensorModel>();
        }
        return this.sensorModel;
    }

    /**
     * Gets the value of the sensor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sensor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSensor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sensor }
     * 
     * 
     */
    public List<Sensor> getSensor() {
        if (sensor == null) {
            sensor = new ArrayList<Sensor>();
        }
        return this.sensor;
    }

    /**
     * Gets the value of the calibration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the calibration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCalibration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Calibration }
     * 
     * 
     */
    public List<Calibration> getCalibration() {
        if (calibration == null) {
            calibration = new ArrayList<Calibration>();
        }
        return this.calibration;
    }

    /**
     * Gets the value of the acknowledgement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acknowledgement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcknowledgement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Acknowledgement }
     * 
     * 
     */
    public List<Acknowledgement> getAcknowledgement() {
        if (acknowledgement == null) {
            acknowledgement = new ArrayList<Acknowledgement>();
        }
        return this.acknowledgement;
    }

}
