//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.11.28 at 03:46:45 PM GMT 
//


package org.nees.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CoordinateSystem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoordinateSystem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="name" type="{}String50"/>
 *         &lt;element name="Dimension1" type="{}CoordinateDimension"/>
 *         &lt;element name="Dimension2" type="{}CoordinateDimension"/>
 *         &lt;element name="Dimension3" type="{}CoordinateDimension"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{}IDnumber" />
 *       &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoordinateSystem", propOrder = {
    "name",
    "dimension1",
    "dimension2",
    "dimension3"
})
public class CoordinateSystem {

    protected String name;
    @XmlElement(name = "Dimension1")
    protected CoordinateDimension dimension1;
    @XmlElement(name = "Dimension2")
    protected CoordinateDimension dimension2;
    @XmlElement(name = "Dimension3")
    protected CoordinateDimension dimension3;
    @XmlAttribute
    protected Integer id;
    @XmlAttribute
    protected String link;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the dimension1 property.
     * 
     * @return
     *     possible object is
     *     {@link CoordinateDimension }
     *     
     */
    public CoordinateDimension getDimension1() {
        return dimension1;
    }

    /**
     * Sets the value of the dimension1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordinateDimension }
     *     
     */
    public void setDimension1(CoordinateDimension value) {
        this.dimension1 = value;
    }

    /**
     * Gets the value of the dimension2 property.
     * 
     * @return
     *     possible object is
     *     {@link CoordinateDimension }
     *     
     */
    public CoordinateDimension getDimension2() {
        return dimension2;
    }

    /**
     * Sets the value of the dimension2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordinateDimension }
     *     
     */
    public void setDimension2(CoordinateDimension value) {
        this.dimension2 = value;
    }

    /**
     * Gets the value of the dimension3 property.
     * 
     * @return
     *     possible object is
     *     {@link CoordinateDimension }
     *     
     */
    public CoordinateDimension getDimension3() {
        return dimension3;
    }

    /**
     * Sets the value of the dimension3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordinateDimension }
     *     
     */
    public void setDimension3(CoordinateDimension value) {
        this.dimension3 = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLink(String value) {
        this.link = value;
    }

}
