//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.11.28 at 03:46:45 PM GMT 
//


package org.nees.data;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Equipment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Equipment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="EquipmentClass" type="{}EquipmentClass"/>
 *         &lt;element name="parentId" type="{}IDnumber"/>
 *         &lt;element name="isMajor">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="TRUE"/>
 *               &lt;enumeration value="FALSE"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="neesOperated">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="NO"/>
 *               &lt;enumeration value="PARTIALLY"/>
 *               &lt;enumeration value="FULLY"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="name" type="{}String128"/>
 *         &lt;element name="manufacturer" type="{}String128"/>
 *         &lt;element name="supplier" type="{}String128"/>
 *         &lt;element name="owner" type="{}String128"/>
 *         &lt;element name="modelNumber" type="{}String255"/>
 *         &lt;element name="isSeparateScheduling">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="TRUE"/>
 *               &lt;enumeration value="FALSE"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="serialNumber" type="{}String255"/>
 *         &lt;element name="commissionDate" type="{}Date"/>
 *         &lt;element name="calibrationInformation" type="{}String255"/>
 *         &lt;element name="note" type="{}Text"/>
 *         &lt;element name="labAssignedId" type="{}String255"/>
 *         &lt;element name="quantity" type="{}Int"/>
 *         &lt;element name="additionalSpecPageCount" type="{}SmallInt"/>
 *         &lt;element name="manufacturerDocPageCount" type="{}SmallInt"/>
 *         &lt;element name="designConsiderationPageCount" type="{}SmallInt"/>
 *         &lt;element name="subcomponentsDocPageCount" type="{}SmallInt"/>
 *         &lt;element name="interfaceDocPageCount" type="{}SmallInt"/>
 *         &lt;element name="deleted">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="TRUE"/>
 *               &lt;enumeration value="FALSE"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AdditionalSpecFile" type="{}DataFile"/>
 *         &lt;element name="ManufacturerDocFile" type="{}DataFile"/>
 *         &lt;element name="DesignConsiderationFile" type="{}DataFile"/>
 *         &lt;element name="SubcomponentsDocFile" type="{}DataFile"/>
 *         &lt;element name="InterfaceDocFile" type="{}DataFile"/>
 *         &lt;element name="EquipmentDocumentation" type="{}EquipmentDocumentation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EquipmentAttribute" type="{}EquipmentAttribute" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{}IDnumber" />
 *       &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Equipment", propOrder = {
    "equipmentClass",
    "parentId",
    "isMajor",
    "neesOperated",
    "name",
    "manufacturer",
    "supplier",
    "owner",
    "modelNumber",
    "isSeparateScheduling",
    "serialNumber",
    "commissionDate",
    "calibrationInformation",
    "note",
    "labAssignedId",
    "quantity",
    "additionalSpecPageCount",
    "manufacturerDocPageCount",
    "designConsiderationPageCount",
    "subcomponentsDocPageCount",
    "interfaceDocPageCount",
    "deleted",
    "additionalSpecFile",
    "manufacturerDocFile",
    "designConsiderationFile",
    "subcomponentsDocFile",
    "interfaceDocFile",
    "equipmentDocumentation",
    "equipmentAttribute"
})
public class Equipment {

    @XmlElementRef(name = "EquipmentClass", type = JAXBElement.class)
    protected JAXBElement<EquipmentClass> equipmentClass;
    @XmlElementRef(name = "parentId", type = JAXBElement.class)
    protected JAXBElement<Integer> parentId;
    @XmlElementRef(name = "isMajor", type = JAXBElement.class)
    protected JAXBElement<String> isMajor;
    @XmlElementRef(name = "neesOperated", type = JAXBElement.class)
    protected JAXBElement<String> neesOperated;
    @XmlElementRef(name = "name", type = JAXBElement.class)
    protected JAXBElement<String> name;
    @XmlElementRef(name = "manufacturer", type = JAXBElement.class)
    protected JAXBElement<String> manufacturer;
    @XmlElementRef(name = "supplier", type = JAXBElement.class)
    protected JAXBElement<String> supplier;
    @XmlElementRef(name = "owner", type = JAXBElement.class)
    protected JAXBElement<String> owner;
    @XmlElementRef(name = "modelNumber", type = JAXBElement.class)
    protected JAXBElement<String> modelNumber;
    @XmlElementRef(name = "isSeparateScheduling", type = JAXBElement.class)
    protected JAXBElement<String> isSeparateScheduling;
    @XmlElementRef(name = "serialNumber", type = JAXBElement.class)
    protected JAXBElement<String> serialNumber;
    @XmlElementRef(name = "commissionDate", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> commissionDate;
    @XmlElementRef(name = "calibrationInformation", type = JAXBElement.class)
    protected JAXBElement<String> calibrationInformation;
    @XmlElementRef(name = "note", type = JAXBElement.class)
    protected JAXBElement<String> note;
    @XmlElementRef(name = "labAssignedId", type = JAXBElement.class)
    protected JAXBElement<String> labAssignedId;
    @XmlElementRef(name = "quantity", type = JAXBElement.class)
    protected JAXBElement<Integer> quantity;
    @XmlElementRef(name = "additionalSpecPageCount", type = JAXBElement.class)
    protected JAXBElement<Integer> additionalSpecPageCount;
    @XmlElementRef(name = "manufacturerDocPageCount", type = JAXBElement.class)
    protected JAXBElement<Integer> manufacturerDocPageCount;
    @XmlElementRef(name = "designConsiderationPageCount", type = JAXBElement.class)
    protected JAXBElement<Integer> designConsiderationPageCount;
    @XmlElementRef(name = "subcomponentsDocPageCount", type = JAXBElement.class)
    protected JAXBElement<Integer> subcomponentsDocPageCount;
    @XmlElementRef(name = "interfaceDocPageCount", type = JAXBElement.class)
    protected JAXBElement<Integer> interfaceDocPageCount;
    @XmlElement(defaultValue = "FALSE")
    protected String deleted;
    @XmlElementRef(name = "AdditionalSpecFile", type = JAXBElement.class)
    protected JAXBElement<DataFile> additionalSpecFile;
    @XmlElementRef(name = "ManufacturerDocFile", type = JAXBElement.class)
    protected JAXBElement<DataFile> manufacturerDocFile;
    @XmlElementRef(name = "DesignConsiderationFile", type = JAXBElement.class)
    protected JAXBElement<DataFile> designConsiderationFile;
    @XmlElementRef(name = "SubcomponentsDocFile", type = JAXBElement.class)
    protected JAXBElement<DataFile> subcomponentsDocFile;
    @XmlElementRef(name = "InterfaceDocFile", type = JAXBElement.class)
    protected JAXBElement<DataFile> interfaceDocFile;
    @XmlElement(name = "EquipmentDocumentation")
    protected List<EquipmentDocumentation> equipmentDocumentation;
    @XmlElement(name = "EquipmentAttribute")
    protected List<EquipmentAttribute> equipmentAttribute;
    @XmlAttribute
    protected Integer id;
    @XmlAttribute
    protected String link;

    /**
     * Gets the value of the equipmentClass property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link EquipmentClass }{@code >}
     *     
     */
    public JAXBElement<EquipmentClass> getEquipmentClass() {
        return equipmentClass;
    }

    /**
     * Sets the value of the equipmentClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link EquipmentClass }{@code >}
     *     
     */
    public void setEquipmentClass(JAXBElement<EquipmentClass> value) {
        this.equipmentClass = ((JAXBElement<EquipmentClass> ) value);
    }

    /**
     * Gets the value of the parentId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getParentId() {
        return parentId;
    }

    /**
     * Sets the value of the parentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setParentId(JAXBElement<Integer> value) {
        this.parentId = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the isMajor property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getIsMajor() {
        return isMajor;
    }

    /**
     * Sets the value of the isMajor property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setIsMajor(JAXBElement<String> value) {
        this.isMajor = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the neesOperated property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getNeesOperated() {
        return neesOperated;
    }

    /**
     * Sets the value of the neesOperated property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNeesOperated(JAXBElement<String> value) {
        this.neesOperated = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setName(JAXBElement<String> value) {
        this.name = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setManufacturer(JAXBElement<String> value) {
        this.manufacturer = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the supplier property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSupplier() {
        return supplier;
    }

    /**
     * Sets the value of the supplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSupplier(JAXBElement<String> value) {
        this.supplier = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOwner(JAXBElement<String> value) {
        this.owner = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the modelNumber property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getModelNumber() {
        return modelNumber;
    }

    /**
     * Sets the value of the modelNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setModelNumber(JAXBElement<String> value) {
        this.modelNumber = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the isSeparateScheduling property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getIsSeparateScheduling() {
        return isSeparateScheduling;
    }

    /**
     * Sets the value of the isSeparateScheduling property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setIsSeparateScheduling(JAXBElement<String> value) {
        this.isSeparateScheduling = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the serialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSerialNumber(JAXBElement<String> value) {
        this.serialNumber = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the commissionDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getCommissionDate() {
        return commissionDate;
    }

    /**
     * Sets the value of the commissionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setCommissionDate(JAXBElement<XMLGregorianCalendar> value) {
        this.commissionDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the calibrationInformation property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCalibrationInformation() {
        return calibrationInformation;
    }

    /**
     * Sets the value of the calibrationInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCalibrationInformation(JAXBElement<String> value) {
        this.calibrationInformation = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNote(JAXBElement<String> value) {
        this.note = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the labAssignedId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLabAssignedId() {
        return labAssignedId;
    }

    /**
     * Sets the value of the labAssignedId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLabAssignedId(JAXBElement<String> value) {
        this.labAssignedId = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setQuantity(JAXBElement<Integer> value) {
        this.quantity = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the additionalSpecPageCount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getAdditionalSpecPageCount() {
        return additionalSpecPageCount;
    }

    /**
     * Sets the value of the additionalSpecPageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setAdditionalSpecPageCount(JAXBElement<Integer> value) {
        this.additionalSpecPageCount = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the manufacturerDocPageCount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getManufacturerDocPageCount() {
        return manufacturerDocPageCount;
    }

    /**
     * Sets the value of the manufacturerDocPageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setManufacturerDocPageCount(JAXBElement<Integer> value) {
        this.manufacturerDocPageCount = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the designConsiderationPageCount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getDesignConsiderationPageCount() {
        return designConsiderationPageCount;
    }

    /**
     * Sets the value of the designConsiderationPageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setDesignConsiderationPageCount(JAXBElement<Integer> value) {
        this.designConsiderationPageCount = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the subcomponentsDocPageCount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getSubcomponentsDocPageCount() {
        return subcomponentsDocPageCount;
    }

    /**
     * Sets the value of the subcomponentsDocPageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setSubcomponentsDocPageCount(JAXBElement<Integer> value) {
        this.subcomponentsDocPageCount = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the interfaceDocPageCount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getInterfaceDocPageCount() {
        return interfaceDocPageCount;
    }

    /**
     * Sets the value of the interfaceDocPageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setInterfaceDocPageCount(JAXBElement<Integer> value) {
        this.interfaceDocPageCount = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the deleted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * Sets the value of the deleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeleted(String value) {
        this.deleted = value;
    }

    /**
     * Gets the value of the additionalSpecFile property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DataFile }{@code >}
     *     
     */
    public JAXBElement<DataFile> getAdditionalSpecFile() {
        return additionalSpecFile;
    }

    /**
     * Sets the value of the additionalSpecFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DataFile }{@code >}
     *     
     */
    public void setAdditionalSpecFile(JAXBElement<DataFile> value) {
        this.additionalSpecFile = ((JAXBElement<DataFile> ) value);
    }

    /**
     * Gets the value of the manufacturerDocFile property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DataFile }{@code >}
     *     
     */
    public JAXBElement<DataFile> getManufacturerDocFile() {
        return manufacturerDocFile;
    }

    /**
     * Sets the value of the manufacturerDocFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DataFile }{@code >}
     *     
     */
    public void setManufacturerDocFile(JAXBElement<DataFile> value) {
        this.manufacturerDocFile = ((JAXBElement<DataFile> ) value);
    }

    /**
     * Gets the value of the designConsiderationFile property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DataFile }{@code >}
     *     
     */
    public JAXBElement<DataFile> getDesignConsiderationFile() {
        return designConsiderationFile;
    }

    /**
     * Sets the value of the designConsiderationFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DataFile }{@code >}
     *     
     */
    public void setDesignConsiderationFile(JAXBElement<DataFile> value) {
        this.designConsiderationFile = ((JAXBElement<DataFile> ) value);
    }

    /**
     * Gets the value of the subcomponentsDocFile property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DataFile }{@code >}
     *     
     */
    public JAXBElement<DataFile> getSubcomponentsDocFile() {
        return subcomponentsDocFile;
    }

    /**
     * Sets the value of the subcomponentsDocFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DataFile }{@code >}
     *     
     */
    public void setSubcomponentsDocFile(JAXBElement<DataFile> value) {
        this.subcomponentsDocFile = ((JAXBElement<DataFile> ) value);
    }

    /**
     * Gets the value of the interfaceDocFile property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DataFile }{@code >}
     *     
     */
    public JAXBElement<DataFile> getInterfaceDocFile() {
        return interfaceDocFile;
    }

    /**
     * Sets the value of the interfaceDocFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DataFile }{@code >}
     *     
     */
    public void setInterfaceDocFile(JAXBElement<DataFile> value) {
        this.interfaceDocFile = ((JAXBElement<DataFile> ) value);
    }

    /**
     * Gets the value of the equipmentDocumentation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipmentDocumentation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipmentDocumentation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EquipmentDocumentation }
     * 
     * 
     */
    public List<EquipmentDocumentation> getEquipmentDocumentation() {
        if (equipmentDocumentation == null) {
            equipmentDocumentation = new ArrayList<EquipmentDocumentation>();
        }
        return this.equipmentDocumentation;
    }

    /**
     * Gets the value of the equipmentAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipmentAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipmentAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EquipmentAttribute }
     * 
     * 
     */
    public List<EquipmentAttribute> getEquipmentAttribute() {
        if (equipmentAttribute == null) {
            equipmentAttribute = new ArrayList<EquipmentAttribute>();
        }
        return this.equipmentAttribute;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLink(String value) {
        this.link = value;
    }

}
