//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.11.28 at 03:46:45 PM GMT 
//


package org.nees.data;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Facility complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Facility">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="sysadmin" type="{}String255" minOccurs="0"/>
 *         &lt;element name="sysadminEmail" type="{}String255" minOccurs="0"/>
 *         &lt;element name="sysadminUser" type="{}String255" minOccurs="0"/>
 *         &lt;element name="siteOpUser" type="{}String255" minOccurs="0"/>
 *         &lt;element name="shortName" type="{}String255"/>
 *         &lt;element name="flexTPS_URL" type="{}URL255" minOccurs="0"/>
 *         &lt;element name="pop_URL" type="{}URL255" minOccurs="0"/>
 *         &lt;element name="website_URL" type="{}URL255" minOccurs="0"/>
 *         &lt;element name="nawiStatus" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="NEES"/>
 *               &lt;enumeration value="NON_NEES"/>
 *               &lt;enumeration value="SHARED"/>
 *               &lt;enumeration value="FLEX"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="timezone" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nawiAdminUsers" type="{}String255" minOccurs="0"/>
 *         &lt;element name="image_URL" type="{}URL255" minOccurs="0"/>
 *         &lt;element name="sitename" type="{}String255" minOccurs="0"/>
 *         &lt;element name="department" type="{}String255" minOccurs="0"/>
 *         &lt;element name="laboratory" type="{}String255" minOccurs="0"/>
 *         &lt;element name="nsfAcknowledgement" type="{}Text" minOccurs="0"/>
 *         &lt;element name="nsfAward_URL" type="{}URL255" minOccurs="0"/>
 *         &lt;element name="siteIntroductionFile" type="{}DataFile" minOccurs="0"/>
 *         &lt;element name="siteDescriptionFile" type="{}DataFile" minOccurs="0"/>
 *         &lt;element name="historyFile" type="{}DataFile" minOccurs="0"/>
 *         &lt;element name="VisitorInformation" type="{}VisitorInformation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TrainingAndCertification" type="{}TrainingAndCertification" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Equipment" type="{}Equipment" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{}IDnumber" />
 *       &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Facility", propOrder = {
    "sysadmin",
    "sysadminEmail",
    "sysadminUser",
    "siteOpUser",
    "shortName",
    "flexTPSURL",
    "popURL",
    "websiteURL",
    "nawiStatus",
    "timezone",
    "nawiAdminUsers",
    "imageURL",
    "sitename",
    "department",
    "laboratory",
    "nsfAcknowledgement",
    "nsfAwardURL",
    "siteIntroductionFile",
    "siteDescriptionFile",
    "historyFile",
    "visitorInformation",
    "trainingAndCertification",
    "equipment"
})
public class Facility {

    protected String sysadmin;
    protected String sysadminEmail;
    protected String sysadminUser;
    protected String siteOpUser;
    protected String shortName;
    @XmlElement(name = "flexTPS_URL")
    protected String flexTPSURL;
    @XmlElement(name = "pop_URL")
    protected String popURL;
    @XmlElement(name = "website_URL")
    protected String websiteURL;
    protected String nawiStatus;
    protected String timezone;
    protected String nawiAdminUsers;
    @XmlElement(name = "image_URL")
    protected String imageURL;
    protected String sitename;
    protected String department;
    protected String laboratory;
    protected String nsfAcknowledgement;
    @XmlElement(name = "nsfAward_URL")
    protected String nsfAwardURL;
    protected DataFile siteIntroductionFile;
    protected DataFile siteDescriptionFile;
    protected DataFile historyFile;
    @XmlElement(name = "VisitorInformation")
    protected List<VisitorInformation> visitorInformation;
    @XmlElement(name = "TrainingAndCertification")
    protected List<TrainingAndCertification> trainingAndCertification;
    @XmlElement(name = "Equipment")
    protected List<Equipment> equipment;
    @XmlAttribute
    protected Integer id;
    @XmlAttribute
    protected String link;

    /**
     * Gets the value of the sysadmin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSysadmin() {
        return sysadmin;
    }

    /**
     * Sets the value of the sysadmin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSysadmin(String value) {
        this.sysadmin = value;
    }

    /**
     * Gets the value of the sysadminEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSysadminEmail() {
        return sysadminEmail;
    }

    /**
     * Sets the value of the sysadminEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSysadminEmail(String value) {
        this.sysadminEmail = value;
    }

    /**
     * Gets the value of the sysadminUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSysadminUser() {
        return sysadminUser;
    }

    /**
     * Sets the value of the sysadminUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSysadminUser(String value) {
        this.sysadminUser = value;
    }

    /**
     * Gets the value of the siteOpUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteOpUser() {
        return siteOpUser;
    }

    /**
     * Sets the value of the siteOpUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteOpUser(String value) {
        this.siteOpUser = value;
    }

    /**
     * Gets the value of the shortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortName(String value) {
        this.shortName = value;
    }

    /**
     * Gets the value of the flexTPSURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlexTPSURL() {
        return flexTPSURL;
    }

    /**
     * Sets the value of the flexTPSURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlexTPSURL(String value) {
        this.flexTPSURL = value;
    }

    /**
     * Gets the value of the popURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPopURL() {
        return popURL;
    }

    /**
     * Sets the value of the popURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPopURL(String value) {
        this.popURL = value;
    }

    /**
     * Gets the value of the websiteURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebsiteURL() {
        return websiteURL;
    }

    /**
     * Sets the value of the websiteURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebsiteURL(String value) {
        this.websiteURL = value;
    }

    /**
     * Gets the value of the nawiStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNawiStatus() {
        return nawiStatus;
    }

    /**
     * Sets the value of the nawiStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNawiStatus(String value) {
        this.nawiStatus = value;
    }

    /**
     * Gets the value of the timezone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimezone() {
        return timezone;
    }

    /**
     * Sets the value of the timezone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimezone(String value) {
        this.timezone = value;
    }

    /**
     * Gets the value of the nawiAdminUsers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNawiAdminUsers() {
        return nawiAdminUsers;
    }

    /**
     * Sets the value of the nawiAdminUsers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNawiAdminUsers(String value) {
        this.nawiAdminUsers = value;
    }

    /**
     * Gets the value of the imageURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageURL() {
        return imageURL;
    }

    /**
     * Sets the value of the imageURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageURL(String value) {
        this.imageURL = value;
    }

    /**
     * Gets the value of the sitename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSitename() {
        return sitename;
    }

    /**
     * Sets the value of the sitename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSitename(String value) {
        this.sitename = value;
    }

    /**
     * Gets the value of the department property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartment() {
        return department;
    }

    /**
     * Sets the value of the department property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartment(String value) {
        this.department = value;
    }

    /**
     * Gets the value of the laboratory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLaboratory() {
        return laboratory;
    }

    /**
     * Sets the value of the laboratory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLaboratory(String value) {
        this.laboratory = value;
    }

    /**
     * Gets the value of the nsfAcknowledgement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsfAcknowledgement() {
        return nsfAcknowledgement;
    }

    /**
     * Sets the value of the nsfAcknowledgement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNsfAcknowledgement(String value) {
        this.nsfAcknowledgement = value;
    }

    /**
     * Gets the value of the nsfAwardURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsfAwardURL() {
        return nsfAwardURL;
    }

    /**
     * Sets the value of the nsfAwardURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNsfAwardURL(String value) {
        this.nsfAwardURL = value;
    }

    /**
     * Gets the value of the siteIntroductionFile property.
     * 
     * @return
     *     possible object is
     *     {@link DataFile }
     *     
     */
    public DataFile getSiteIntroductionFile() {
        return siteIntroductionFile;
    }

    /**
     * Sets the value of the siteIntroductionFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataFile }
     *     
     */
    public void setSiteIntroductionFile(DataFile value) {
        this.siteIntroductionFile = value;
    }

    /**
     * Gets the value of the siteDescriptionFile property.
     * 
     * @return
     *     possible object is
     *     {@link DataFile }
     *     
     */
    public DataFile getSiteDescriptionFile() {
        return siteDescriptionFile;
    }

    /**
     * Sets the value of the siteDescriptionFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataFile }
     *     
     */
    public void setSiteDescriptionFile(DataFile value) {
        this.siteDescriptionFile = value;
    }

    /**
     * Gets the value of the historyFile property.
     * 
     * @return
     *     possible object is
     *     {@link DataFile }
     *     
     */
    public DataFile getHistoryFile() {
        return historyFile;
    }

    /**
     * Sets the value of the historyFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataFile }
     *     
     */
    public void setHistoryFile(DataFile value) {
        this.historyFile = value;
    }

    /**
     * Gets the value of the visitorInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the visitorInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVisitorInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VisitorInformation }
     * 
     * 
     */
    public List<VisitorInformation> getVisitorInformation() {
        if (visitorInformation == null) {
            visitorInformation = new ArrayList<VisitorInformation>();
        }
        return this.visitorInformation;
    }

    /**
     * Gets the value of the trainingAndCertification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trainingAndCertification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrainingAndCertification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrainingAndCertification }
     * 
     * 
     */
    public List<TrainingAndCertification> getTrainingAndCertification() {
        if (trainingAndCertification == null) {
            trainingAndCertification = new ArrayList<TrainingAndCertification>();
        }
        return this.trainingAndCertification;
    }

    /**
     * Gets the value of the equipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Equipment }
     * 
     * 
     */
    public List<Equipment> getEquipment() {
        if (equipment == null) {
            equipment = new ArrayList<Equipment>();
        }
        return this.equipment;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLink(String value) {
        this.link = value;
    }

}
