//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.11.28 at 03:46:45 PM GMT 
//


package org.nees.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for NAWI complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NAWI">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="exp_name" type="{}String255"/>
 *         &lt;element name="exp_descript" type="{}Text"/>
 *         &lt;element name="exp_phase">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="test_dt" type="{}Timestamp"/>
 *         &lt;element name="test_start" type="{}Date"/>
 *         &lt;element name="test_end" type="{}Date"/>
 *         &lt;element name="test_tz">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="contact_name" type="{}String255"/>
 *         &lt;element name="contact_email" type="{}String255"/>
 *         &lt;element name="movie_url" type="{}String255"/>
 *         &lt;element name="active">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
 *               &lt;maxInclusive value="255"/>
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{}IDnumber" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NAWI", propOrder = {
    "expName",
    "expDescript",
    "expPhase",
    "testDt",
    "testStart",
    "testEnd",
    "testTz",
    "contactName",
    "contactEmail",
    "movieUrl",
    "active"
})
public class NAWI {

    @XmlElementRef(name = "exp_name", type = JAXBElement.class)
    protected JAXBElement<String> expName;
    @XmlElementRef(name = "exp_descript", type = JAXBElement.class)
    protected JAXBElement<String> expDescript;
    @XmlElement(name = "exp_phase", defaultValue = "DESIGN")
    protected String expPhase;
    @XmlElementRef(name = "test_dt", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> testDt;
    @XmlElementRef(name = "test_start", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> testStart;
    @XmlElementRef(name = "test_end", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> testEnd;
    @XmlElementRef(name = "test_tz", type = JAXBElement.class)
    protected JAXBElement<String> testTz;
    @XmlElementRef(name = "contact_name", type = JAXBElement.class)
    protected JAXBElement<String> contactName;
    @XmlElementRef(name = "contact_email", type = JAXBElement.class)
    protected JAXBElement<String> contactEmail;
    @XmlElementRef(name = "movie_url", type = JAXBElement.class)
    protected JAXBElement<String> movieUrl;
    @XmlElementRef(name = "active", type = JAXBElement.class)
    protected JAXBElement<Short> active;
    @XmlAttribute
    protected Integer id;

    /**
     * Gets the value of the expName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getExpName() {
        return expName;
    }

    /**
     * Sets the value of the expName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setExpName(JAXBElement<String> value) {
        this.expName = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the expDescript property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getExpDescript() {
        return expDescript;
    }

    /**
     * Sets the value of the expDescript property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setExpDescript(JAXBElement<String> value) {
        this.expDescript = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the expPhase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpPhase() {
        return expPhase;
    }

    /**
     * Sets the value of the expPhase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpPhase(String value) {
        this.expPhase = value;
    }

    /**
     * Gets the value of the testDt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getTestDt() {
        return testDt;
    }

    /**
     * Sets the value of the testDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setTestDt(JAXBElement<XMLGregorianCalendar> value) {
        this.testDt = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the testStart property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getTestStart() {
        return testStart;
    }

    /**
     * Sets the value of the testStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setTestStart(JAXBElement<XMLGregorianCalendar> value) {
        this.testStart = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the testEnd property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getTestEnd() {
        return testEnd;
    }

    /**
     * Sets the value of the testEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setTestEnd(JAXBElement<XMLGregorianCalendar> value) {
        this.testEnd = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the testTz property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTestTz() {
        return testTz;
    }

    /**
     * Sets the value of the testTz property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTestTz(JAXBElement<String> value) {
        this.testTz = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the contactName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getContactName() {
        return contactName;
    }

    /**
     * Sets the value of the contactName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setContactName(JAXBElement<String> value) {
        this.contactName = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the contactEmail property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getContactEmail() {
        return contactEmail;
    }

    /**
     * Sets the value of the contactEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setContactEmail(JAXBElement<String> value) {
        this.contactEmail = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the movieUrl property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMovieUrl() {
        return movieUrl;
    }

    /**
     * Sets the value of the movieUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMovieUrl(JAXBElement<String> value) {
        this.movieUrl = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the active property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Short }{@code >}
     *     
     */
    public JAXBElement<Short> getActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Short }{@code >}
     *     
     */
    public void setActive(JAXBElement<Short> value) {
        this.active = ((JAXBElement<Short> ) value);
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

}
