//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.11.28 at 03:46:45 PM GMT 
//


package org.nees.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SensorGroupedAttrMap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SensorGroupedAttrMap">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="gAttributeId" use="required" type="{}IDnumber" />
 *       &lt;attribute name="groupValue" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SensorGroupedAttrMap")
public class SensorGroupedAttrMap {

    @XmlAttribute(required = true)
    protected int gAttributeId;
    @XmlAttribute(required = true)
    protected int groupValue;

    /**
     * Gets the value of the gAttributeId property.
     * 
     */
    public int getGAttributeId() {
        return gAttributeId;
    }

    /**
     * Sets the value of the gAttributeId property.
     * 
     */
    public void setGAttributeId(int value) {
        this.gAttributeId = value;
    }

    /**
     * Gets the value of the groupValue property.
     * 
     */
    public int getGroupValue() {
        return groupValue;
    }

    /**
     * Sets the value of the groupValue property.
     * 
     */
    public void setGroupValue(int value) {
        this.groupValue = value;
    }

}
