//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.11.28 at 03:46:45 PM GMT 
//


package org.nees.data;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SensorModel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SensorModel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="name" type="{}String50"/>
 *         &lt;element name="SensorType" type="{}SensorType" minOccurs="0"/>
 *         &lt;element name="model" type="{}String50"/>
 *         &lt;element name="manufacturer" type="{}String50"/>
 *         &lt;element name="description" type="{}String255"/>
 *         &lt;element name="signalType" type="{}String50"/>
 *         &lt;element name="minMeasuredValue" type="{}Double"/>
 *         &lt;element name="maxMeasuredValue" type="{}Double"/>
 *         &lt;element name="measuredValueUnits">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="sensitivity" type="{}Double"/>
 *         &lt;element name="sensitivityUnits">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="minOpTemp" type="{}SmallInt"/>
 *         &lt;element name="maxOpTemp" type="{}SmallInt"/>
 *         &lt;element name="tempUnits">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="note" type="{}String255"/>
 *         &lt;element name="deleted">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="FALSE"/>
 *               &lt;enumeration value="TRUE"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Sensor" type="{}Sensor" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{}IDnumber" />
 *       &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SensorModel", propOrder = {
    "name",
    "sensorType",
    "model",
    "manufacturer",
    "description",
    "signalType",
    "minMeasuredValue",
    "maxMeasuredValue",
    "measuredValueUnits",
    "sensitivity",
    "sensitivityUnits",
    "minOpTemp",
    "maxOpTemp",
    "tempUnits",
    "note",
    "deleted",
    "sensor"
})
public class SensorModel {

    @XmlElementRef(name = "name", type = JAXBElement.class)
    protected JAXBElement<String> name;
    @XmlElement(name = "SensorType")
    protected SensorType sensorType;
    @XmlElementRef(name = "model", type = JAXBElement.class)
    protected JAXBElement<String> model;
    @XmlElementRef(name = "manufacturer", type = JAXBElement.class)
    protected JAXBElement<String> manufacturer;
    @XmlElementRef(name = "description", type = JAXBElement.class)
    protected JAXBElement<String> description;
    @XmlElementRef(name = "signalType", type = JAXBElement.class)
    protected JAXBElement<String> signalType;
    @XmlElementRef(name = "minMeasuredValue", type = JAXBElement.class)
    protected JAXBElement<Double> minMeasuredValue;
    @XmlElementRef(name = "maxMeasuredValue", type = JAXBElement.class)
    protected JAXBElement<Double> maxMeasuredValue;
    @XmlElementRef(name = "measuredValueUnits", type = JAXBElement.class)
    protected JAXBElement<String> measuredValueUnits;
    @XmlElementRef(name = "sensitivity", type = JAXBElement.class)
    protected JAXBElement<Double> sensitivity;
    @XmlElementRef(name = "sensitivityUnits", type = JAXBElement.class)
    protected JAXBElement<String> sensitivityUnits;
    @XmlElementRef(name = "minOpTemp", type = JAXBElement.class)
    protected JAXBElement<Integer> minOpTemp;
    @XmlElementRef(name = "maxOpTemp", type = JAXBElement.class)
    protected JAXBElement<Integer> maxOpTemp;
    @XmlElementRef(name = "tempUnits", type = JAXBElement.class)
    protected JAXBElement<String> tempUnits;
    @XmlElementRef(name = "note", type = JAXBElement.class)
    protected JAXBElement<String> note;
    @XmlElement(defaultValue = "FALSE")
    protected String deleted;
    @XmlElement(name = "Sensor")
    protected List<Sensor> sensor;
    @XmlAttribute
    protected Integer id;
    @XmlAttribute
    protected String link;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setName(JAXBElement<String> value) {
        this.name = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the sensorType property.
     * 
     * @return
     *     possible object is
     *     {@link SensorType }
     *     
     */
    public SensorType getSensorType() {
        return sensorType;
    }

    /**
     * Sets the value of the sensorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SensorType }
     *     
     */
    public void setSensorType(SensorType value) {
        this.sensorType = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setModel(JAXBElement<String> value) {
        this.model = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setManufacturer(JAXBElement<String> value) {
        this.manufacturer = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDescription(JAXBElement<String> value) {
        this.description = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the signalType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSignalType() {
        return signalType;
    }

    /**
     * Sets the value of the signalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSignalType(JAXBElement<String> value) {
        this.signalType = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the minMeasuredValue property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public JAXBElement<Double> getMinMeasuredValue() {
        return minMeasuredValue;
    }

    /**
     * Sets the value of the minMeasuredValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public void setMinMeasuredValue(JAXBElement<Double> value) {
        this.minMeasuredValue = ((JAXBElement<Double> ) value);
    }

    /**
     * Gets the value of the maxMeasuredValue property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public JAXBElement<Double> getMaxMeasuredValue() {
        return maxMeasuredValue;
    }

    /**
     * Sets the value of the maxMeasuredValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public void setMaxMeasuredValue(JAXBElement<Double> value) {
        this.maxMeasuredValue = ((JAXBElement<Double> ) value);
    }

    /**
     * Gets the value of the measuredValueUnits property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMeasuredValueUnits() {
        return measuredValueUnits;
    }

    /**
     * Sets the value of the measuredValueUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMeasuredValueUnits(JAXBElement<String> value) {
        this.measuredValueUnits = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the sensitivity property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public JAXBElement<Double> getSensitivity() {
        return sensitivity;
    }

    /**
     * Sets the value of the sensitivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public void setSensitivity(JAXBElement<Double> value) {
        this.sensitivity = ((JAXBElement<Double> ) value);
    }

    /**
     * Gets the value of the sensitivityUnits property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSensitivityUnits() {
        return sensitivityUnits;
    }

    /**
     * Sets the value of the sensitivityUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSensitivityUnits(JAXBElement<String> value) {
        this.sensitivityUnits = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the minOpTemp property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getMinOpTemp() {
        return minOpTemp;
    }

    /**
     * Sets the value of the minOpTemp property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setMinOpTemp(JAXBElement<Integer> value) {
        this.minOpTemp = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the maxOpTemp property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getMaxOpTemp() {
        return maxOpTemp;
    }

    /**
     * Sets the value of the maxOpTemp property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setMaxOpTemp(JAXBElement<Integer> value) {
        this.maxOpTemp = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the tempUnits property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTempUnits() {
        return tempUnits;
    }

    /**
     * Sets the value of the tempUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTempUnits(JAXBElement<String> value) {
        this.tempUnits = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNote(JAXBElement<String> value) {
        this.note = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the deleted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * Sets the value of the deleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeleted(String value) {
        this.deleted = value;
    }

    /**
     * Gets the value of the sensor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sensor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSensor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sensor }
     * 
     * 
     */
    public List<Sensor> getSensor() {
        if (sensor == null) {
            sensor = new ArrayList<Sensor>();
        }
        return this.sensor;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLink(String value) {
        this.link = value;
    }

}
