//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.11.28 at 03:46:45 PM GMT 
//


package org.nees.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TC_TCDoc complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TC_TCDoc">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="TCDocId" use="required" type="{}IDnumber" />
 *       &lt;attribute name="trainingCertificationId" use="required" type="{}IDnumber" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TC_TCDoc")
public class TCTCDoc {

    @XmlAttribute(name = "TCDocId", required = true)
    protected int tcDocId;
    @XmlAttribute(required = true)
    protected int trainingCertificationId;

    /**
     * Gets the value of the tcDocId property.
     * 
     */
    public int getTCDocId() {
        return tcDocId;
    }

    /**
     * Sets the value of the tcDocId property.
     * 
     */
    public void setTCDocId(int value) {
        this.tcDocId = value;
    }

    /**
     * Gets the value of the trainingCertificationId property.
     * 
     */
    public int getTrainingCertificationId() {
        return trainingCertificationId;
    }

    /**
     * Sets the value of the trainingCertificationId property.
     * 
     */
    public void setTrainingCertificationId(int value) {
        this.trainingCertificationId = value;
    }

}
