//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.11.28 at 03:46:45 PM GMT 
//


package org.nees.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrainingAndCertification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrainingAndCertification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="safetyPolicyPageCount" type="{}SmallInt"/>
 *         &lt;element name="schedulingFilePageCount" type="{}SmallInt"/>
 *         &lt;element name="rechargeFilePageCount" type="{}SmallInt"/>
 *         &lt;element name="experimentDescriptionPageCount" type="{}SmallInt"/>
 *         &lt;element name="SafetyPolicyFile" type="{}DataFile"/>
 *         &lt;element name="SchedulingFile" type="{}DataFile"/>
 *         &lt;element name="RechargeFile" type="{}DataFile"/>
 *         &lt;element name="ExperimentDescriptionFile" type="{}DataFile"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{}IDnumber" />
 *       &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrainingAndCertification", propOrder = {
    "safetyPolicyPageCount",
    "schedulingFilePageCount",
    "rechargeFilePageCount",
    "experimentDescriptionPageCount",
    "safetyPolicyFile",
    "schedulingFile",
    "rechargeFile",
    "experimentDescriptionFile"
})
public class TrainingAndCertification {

    @XmlElementRef(name = "safetyPolicyPageCount", type = JAXBElement.class)
    protected JAXBElement<Integer> safetyPolicyPageCount;
    @XmlElementRef(name = "schedulingFilePageCount", type = JAXBElement.class)
    protected JAXBElement<Integer> schedulingFilePageCount;
    @XmlElementRef(name = "rechargeFilePageCount", type = JAXBElement.class)
    protected JAXBElement<Integer> rechargeFilePageCount;
    @XmlElementRef(name = "experimentDescriptionPageCount", type = JAXBElement.class)
    protected JAXBElement<Integer> experimentDescriptionPageCount;
    @XmlElementRef(name = "SafetyPolicyFile", type = JAXBElement.class)
    protected JAXBElement<DataFile> safetyPolicyFile;
    @XmlElementRef(name = "SchedulingFile", type = JAXBElement.class)
    protected JAXBElement<DataFile> schedulingFile;
    @XmlElementRef(name = "RechargeFile", type = JAXBElement.class)
    protected JAXBElement<DataFile> rechargeFile;
    @XmlElementRef(name = "ExperimentDescriptionFile", type = JAXBElement.class)
    protected JAXBElement<DataFile> experimentDescriptionFile;
    @XmlAttribute
    protected Integer id;
    @XmlAttribute
    protected String link;

    /**
     * Gets the value of the safetyPolicyPageCount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getSafetyPolicyPageCount() {
        return safetyPolicyPageCount;
    }

    /**
     * Sets the value of the safetyPolicyPageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setSafetyPolicyPageCount(JAXBElement<Integer> value) {
        this.safetyPolicyPageCount = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the schedulingFilePageCount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getSchedulingFilePageCount() {
        return schedulingFilePageCount;
    }

    /**
     * Sets the value of the schedulingFilePageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setSchedulingFilePageCount(JAXBElement<Integer> value) {
        this.schedulingFilePageCount = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the rechargeFilePageCount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getRechargeFilePageCount() {
        return rechargeFilePageCount;
    }

    /**
     * Sets the value of the rechargeFilePageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setRechargeFilePageCount(JAXBElement<Integer> value) {
        this.rechargeFilePageCount = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the experimentDescriptionPageCount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getExperimentDescriptionPageCount() {
        return experimentDescriptionPageCount;
    }

    /**
     * Sets the value of the experimentDescriptionPageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setExperimentDescriptionPageCount(JAXBElement<Integer> value) {
        this.experimentDescriptionPageCount = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the safetyPolicyFile property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DataFile }{@code >}
     *     
     */
    public JAXBElement<DataFile> getSafetyPolicyFile() {
        return safetyPolicyFile;
    }

    /**
     * Sets the value of the safetyPolicyFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DataFile }{@code >}
     *     
     */
    public void setSafetyPolicyFile(JAXBElement<DataFile> value) {
        this.safetyPolicyFile = ((JAXBElement<DataFile> ) value);
    }

    /**
     * Gets the value of the schedulingFile property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DataFile }{@code >}
     *     
     */
    public JAXBElement<DataFile> getSchedulingFile() {
        return schedulingFile;
    }

    /**
     * Sets the value of the schedulingFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DataFile }{@code >}
     *     
     */
    public void setSchedulingFile(JAXBElement<DataFile> value) {
        this.schedulingFile = ((JAXBElement<DataFile> ) value);
    }

    /**
     * Gets the value of the rechargeFile property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DataFile }{@code >}
     *     
     */
    public JAXBElement<DataFile> getRechargeFile() {
        return rechargeFile;
    }

    /**
     * Sets the value of the rechargeFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DataFile }{@code >}
     *     
     */
    public void setRechargeFile(JAXBElement<DataFile> value) {
        this.rechargeFile = ((JAXBElement<DataFile> ) value);
    }

    /**
     * Gets the value of the experimentDescriptionFile property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DataFile }{@code >}
     *     
     */
    public JAXBElement<DataFile> getExperimentDescriptionFile() {
        return experimentDescriptionFile;
    }

    /**
     * Sets the value of the experimentDescriptionFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DataFile }{@code >}
     *     
     */
    public void setExperimentDescriptionFile(JAXBElement<DataFile> value) {
        this.experimentDescriptionFile = ((JAXBElement<DataFile> ) value);
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLink(String value) {
        this.link = value;
    }

}
