//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.11.28 at 03:46:45 PM GMT 
//


package org.nees.data;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Trial complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Trial">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="name" type="{}String16"/>
 *         &lt;element name="title" type="{}String255"/>
 *         &lt;element name="objective" type="{}Text"/>
 *         &lt;element name="description" type="{}Text"/>
 *         &lt;element name="startDate" type="{}Timestamp"/>
 *         &lt;element name="endDate" type="{}Timestamp"/>
 *         &lt;element name="status" type="{}String100"/>
 *         &lt;element name="acceleration" type="{}Float"/>
 *         &lt;element name="baseAcceleration" type="{}Float"/>
 *         &lt;element name="BaseAccelerationUnit" type="{}MeasurementUnit"/>
 *         &lt;element name="motionName" type="{}String255"/>
 *         &lt;element name="station" type="{}String255"/>
 *         &lt;element name="component" type="{}String255"/>
 *         &lt;element name="MotionFile" type="{}DataFile"/>
 *         &lt;element name="Repetition" type="{}Repetition" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DAQConfig" type="{}DAQConfig" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ControllerConfig" type="{}ControllerConfig" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DataFile" type="{}DataFile" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{}IDnumber" />
 *       &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Trial", propOrder = {
    "name",
    "title",
    "objective",
    "description",
    "startDate",
    "endDate",
    "status",
    "acceleration",
    "baseAcceleration",
    "baseAccelerationUnit",
    "motionName",
    "station",
    "component",
    "motionFile",
    "repetition",
    "daqConfig",
    "controllerConfig",
    "dataFile"
})
public class Trial {

    @XmlElementRef(name = "name", type = JAXBElement.class)
    protected JAXBElement<String> name;
    protected String title;
    @XmlElementRef(name = "objective", type = JAXBElement.class)
    protected JAXBElement<String> objective;
    @XmlElementRef(name = "description", type = JAXBElement.class)
    protected JAXBElement<String> description;
    @XmlElementRef(name = "startDate", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> startDate;
    @XmlElementRef(name = "endDate", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> endDate;
    @XmlElementRef(name = "status", type = JAXBElement.class)
    protected JAXBElement<String> status;
    @XmlElementRef(name = "acceleration", type = JAXBElement.class)
    protected JAXBElement<Float> acceleration;
    @XmlElementRef(name = "baseAcceleration", type = JAXBElement.class)
    protected JAXBElement<Float> baseAcceleration;
    @XmlElementRef(name = "BaseAccelerationUnit", type = JAXBElement.class)
    protected JAXBElement<MeasurementUnit> baseAccelerationUnit;
    @XmlElementRef(name = "motionName", type = JAXBElement.class)
    protected JAXBElement<String> motionName;
    @XmlElementRef(name = "station", type = JAXBElement.class)
    protected JAXBElement<String> station;
    @XmlElementRef(name = "component", type = JAXBElement.class)
    protected JAXBElement<String> component;
    @XmlElementRef(name = "MotionFile", type = JAXBElement.class)
    protected JAXBElement<DataFile> motionFile;
    @XmlElement(name = "Repetition", nillable = true)
    protected List<Repetition> repetition;
    @XmlElement(name = "DAQConfig", nillable = true)
    protected List<DAQConfig> daqConfig;
    @XmlElement(name = "ControllerConfig", nillable = true)
    protected List<ControllerConfig> controllerConfig;
    @XmlElement(name = "DataFile", nillable = true)
    protected List<DataFile> dataFile;
    @XmlAttribute
    protected Integer id;
    @XmlAttribute
    protected String link;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setName(JAXBElement<String> value) {
        this.name = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the objective property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getObjective() {
        return objective;
    }

    /**
     * Sets the value of the objective property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setObjective(JAXBElement<String> value) {
        this.objective = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDescription(JAXBElement<String> value) {
        this.description = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setStartDate(JAXBElement<XMLGregorianCalendar> value) {
        this.startDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setEndDate(JAXBElement<XMLGregorianCalendar> value) {
        this.endDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setStatus(JAXBElement<String> value) {
        this.status = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the acceleration property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Float }{@code >}
     *     
     */
    public JAXBElement<Float> getAcceleration() {
        return acceleration;
    }

    /**
     * Sets the value of the acceleration property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Float }{@code >}
     *     
     */
    public void setAcceleration(JAXBElement<Float> value) {
        this.acceleration = ((JAXBElement<Float> ) value);
    }

    /**
     * Gets the value of the baseAcceleration property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Float }{@code >}
     *     
     */
    public JAXBElement<Float> getBaseAcceleration() {
        return baseAcceleration;
    }

    /**
     * Sets the value of the baseAcceleration property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Float }{@code >}
     *     
     */
    public void setBaseAcceleration(JAXBElement<Float> value) {
        this.baseAcceleration = ((JAXBElement<Float> ) value);
    }

    /**
     * Gets the value of the baseAccelerationUnit property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MeasurementUnit }{@code >}
     *     
     */
    public JAXBElement<MeasurementUnit> getBaseAccelerationUnit() {
        return baseAccelerationUnit;
    }

    /**
     * Sets the value of the baseAccelerationUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MeasurementUnit }{@code >}
     *     
     */
    public void setBaseAccelerationUnit(JAXBElement<MeasurementUnit> value) {
        this.baseAccelerationUnit = ((JAXBElement<MeasurementUnit> ) value);
    }

    /**
     * Gets the value of the motionName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMotionName() {
        return motionName;
    }

    /**
     * Sets the value of the motionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMotionName(JAXBElement<String> value) {
        this.motionName = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the station property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getStation() {
        return station;
    }

    /**
     * Sets the value of the station property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setStation(JAXBElement<String> value) {
        this.station = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the component property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getComponent() {
        return component;
    }

    /**
     * Sets the value of the component property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setComponent(JAXBElement<String> value) {
        this.component = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the motionFile property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DataFile }{@code >}
     *     
     */
    public JAXBElement<DataFile> getMotionFile() {
        return motionFile;
    }

    /**
     * Sets the value of the motionFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DataFile }{@code >}
     *     
     */
    public void setMotionFile(JAXBElement<DataFile> value) {
        this.motionFile = ((JAXBElement<DataFile> ) value);
    }

    /**
     * Gets the value of the repetition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the repetition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRepetition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Repetition }
     * 
     * 
     */
    public List<Repetition> getRepetition() {
        if (repetition == null) {
            repetition = new ArrayList<Repetition>();
        }
        return this.repetition;
    }

    /**
     * Gets the value of the daqConfig property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the daqConfig property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDAQConfig().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DAQConfig }
     * 
     * 
     */
    public List<DAQConfig> getDAQConfig() {
        if (daqConfig == null) {
            daqConfig = new ArrayList<DAQConfig>();
        }
        return this.daqConfig;
    }

    /**
     * Gets the value of the controllerConfig property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the controllerConfig property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getControllerConfig().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ControllerConfig }
     * 
     * 
     */
    public List<ControllerConfig> getControllerConfig() {
        if (controllerConfig == null) {
            controllerConfig = new ArrayList<ControllerConfig>();
        }
        return this.controllerConfig;
    }

    /**
     * Gets the value of the dataFile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataFile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataFile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataFile }
     * 
     * 
     */
    public List<DataFile> getDataFile() {
        if (dataFile == null) {
            dataFile = new ArrayList<DataFile>();
        }
        return this.dataFile;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLink(String value) {
        this.link = value;
    }

}
